---
name: Tk-ColourChooser
version: 1.52
author:
  - Tina Mueller
abstract: Perl/Tk module providing a Colour selection dialogue box.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Symbol: 0
  Tk: 0
  strict: 0
  warnings: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Tk::ColourChooser:
    file: lib/Tk/ColourChooser.pm
    version: 1.52
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
